### PR TITLE
Closes #72: Don't require customScan when running programmatically

### LINKED ISSUE #72: TypeError: Cannot read property 'length' of undefined
**Describe the bug**
Unclear from the docs what the required input path is but I've tried I've tried an unpacked Electron dir, the /dist dir (holding a packed Electron app) as well as the .asar file itself - I get the same error:

Package returns `TypeError: Cannot read property 'length' of undefined` in my very simple test.

**To Reproduce**
```
const e_neg = require('@doyensec/electronegativity');
e_neg({
            // input (directory, .js, .html, .asar)
            input: path.join(/path/to/electron, 'dist', 'win-unpacked', 'resources', 'app.asar'),
        })
            .then(result => console.log(result))
            .catch(err => console.error(err));
```

**Expected behavior**
Take the input dir and run the Electron tests.

**Stacktraces**
```
TypeError: Cannot read property 'length' of undefined
    at run (D:\_a\desktop\_config\node_modules\@doyensec\electronegativity\dist\runner.js:78:26)
```

**Platform (please complete the following information):**
Win 10 x64
electronegativity@1.6.0

### PR DESCRIPTION
**Pull request by baltpeter**
`input` is now the only required parameter.

Also made sure that the check names can be passed like the actual class names (with uppercase letters).

### CODE REVIEW

File: src/runner.js [hunk 1]
```diff
@@ -49,6 +49,8 @@ export default async function run(options, forCli = false) {
     } else options.confidenceSet = confidence[options.confidenceSet.toUpperCase()];
   } else options.confidenceSet = confidence["TENTATIVE"]; // default to lowest
 
+  options.customScan = (options.customScan || []).map(c => c.toLowerCase());
```
Comment (phosphore) [inline src/runner.js:52]: Wasn't this already done in:
https://github.com/doyensec/electronegativity/blob/81ae713c0112675e5550146c1b7380f7af4234ba/src/finder/finder.js#L25
and:
https://github.com/doyensec/electronegativity/blob/b7a40b3693f3ade87191f80df5c4c327f6465a53/src/finder/globalchecks.js#L24
Or is it different?

Comment (baltpeter) [reply src/runner.js:52]: The CLI version does the same thing:

https://github.com/doyensec/electronegativity/blob/master/src/index.js#L54

Comment (phosphore) [reply src/runner.js:52]: You are right, I remember writing this check for CLI but I couldn't recall where. LGTM!

**Comment by phosphore** [comment]
Thanks again @baltpeter for taking care of this and sorry for the late review!
